# Generated by Django 5.2.4 on 2025-08-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
            ],
        ),
    ]
